### ISSUE TITLE
Base line algorithms struggle with xaxis

### ISSUE THREAD

**Issue by mhw-hermes** [cbeleites/hyperSpec#1]
The algorithms which use van der monde matrices (spc.fit.poly and spc.rubberband) can not handle higher order polinomials if the xaxis does not match the right criteria. The returned error message is `Error in qr.solve(vdm[use, ], y[use, i]) : singular matrix 'a' in solve`.

The hypothesis for that is that the numerical fitting becomes instable for an axis containing high numbers far away from 0.

The workaround for this problem is to normalise the wavelength axis before doing the fit and recover it afterwards.

**Comment by cbeleites** [comment]
Workaround: 

````
wl.orig <- wl (flu)
tmp <- flu
wl (tmp) <- normalize01 (wl.orig)
bl <- spc.fit.poly(tmp, apply.to = tmp, poly.order = 3)
wl (bl) <- wl.orig
plot (flu)
plot (bl, add = TRUE, col = 2)
````

**Comment by cbeleites** [comment]
Reproduce issue:

````
wl (flu) <- wl (flu) + 1e4
spc.fit.poly(flu, poly.order = 3)
spc.fit.poly.below(flu, poly.order = 3)
````

**Comment by cbeleites** [comment]
Hi Michael, 

I put the basic x-offset option into hyperSpec's code base (master branch).

Now, there is the possiblity to ask `spc.fit.poly` and `spc.fit.poly.below` to return the polynomial coefficient instead of the evaluated polynomial baseline. 
These need to be backtransformed from a_0 (x - ofs)^0 + a_1 (x - ofs)^1 + ... a_n (x - ofs)^n -> a'_0 x^0 + a'_1 x^1 + ... a'_n x^n.

Could you provide a function that does this?

Many thanks,
