### ISSUE TITLE
Use Continuous Integration (CI) service to automatically check hyperSpec package

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#131]
I think continuous integration should be used to check this package automatically. I suggest **GitHub actions** as
-  it is free for open-source projects (with some limitations),
- it can perform checking on all major OS'es (Win, Mac, Linux),
- it is integrated with GitHub.

To enable the CI service, the appropriate setup files should be created. This can be achieved by using one one of these three functions:

```r
usethis::use_github_action_check_standard()
```
```r
usethis::use_github_action_check_release()
```
```r
usethis::use_github_action_check_full()
```
And the setup could be further modified to meet the needs of **hyperSpec** package.

**Comment by cbeleites** [comment]
Hi @GegznaV,

yes, we're planning to do this. At the moment this is difficult due to the need for `git lfs` (where I just ran into quota trouble) and the rather unusually heavy `Makefile`s. 

But: one of the big topics for the Google Summer of Code project is to get **hyperSpec** into a more lean state with continuous integration (and also build a web site with **pkgdown**). 

BTW, we set up a slack workspace, and we have weekly video meetings where we discuss how to do things. I'd be happy to add/invite you to both if you wish.  
Anything that we think should be discussed/known in public will happen via issues, though.

**Comment by GegznaV** [comment]
> I'll therefore label this issue as blocked for now.

I also think that the structure of the GitHub repository should change before CI is activated.

> I'd be happy to add/invite you to both if you wish.

It would be nice to be invited.

**Comment by GegznaV** [comment]
_Offtopic:_ @cbeleites, I added emojis to some labels, e.g.:
![image](https://user-images.githubusercontent.com/12725868/82257242-5a5a5100-9960-11ea-9f29-4f52818009e6.png)
If you are against them, I'll remove the emojis.

**Comment by cbeleites** [comment]
@GegznaV can you please send me an email - I don't have your address to invite you to the slack...

**Comment by GegznaV** [comment]
GegznaV [at] gmail com

**Comment by ximeg** [comment]
@GegznaV I deleted your email from here and invited you to the Slack channel!

**Comment by GegznaV** [comment]
> I'll therefore label this issue as blocked for now.

The issue is overcome in #159 so I removed "blocked" label.
