### ISSUE TITLE
as.character() on quosures deprecated

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#139]
> Warning: Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.

happens e.g. when building the *plotting* vignette.

The calls to `as.character()` should be replaced by `rlang::as_label()`:

- qplot.R: 
  - [x] in `qplotmap`
  - [x] in `qplotc` 
  - [x] check `make.fn.expr()`
- qplotmixmap.R: has different treatment for **ggplot2** < 2.3.0 (2 years ago, #73) -> this can be removed by now
  - [x] `qmixtile()`
  - [x] `qplotmixmap()`

**Comment by yuliaUU** [comment]
what will be analogue of `enquo()`? I get the same message when i use this command in
`facet_wrap(formula(paste("~", enquo(facet_by), collapse = " "))`

**Comment by GegznaV** [comment]
@yuliaUU, is the issue present if you use https://r-hyperspec.github.io/hySpc.ggplot2/ ?

**Comment by GegznaV** [comment]
Otherwise, provide a reprex (https://reprex.tidyverse.org/).

---

On the other hand, this might be a question, related to programming with Tidyverse. In this case, `hyperSpec` repository is not the best place to get Tidyverse-related answers. 
Still, it would help if you studied these, as they might contain the required theory:

- https://ggplot2-book.org/programming.html
- https://dplyr.tidyverse.org/articles/programming.html
- https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html
- https://rlang.r-lib.org/
- https://rlang.r-lib.org/reference/embrace-operator.html
- https://rlang.r-lib.org/reference/enquo.html

What's more, is `facet_wrap(vars(facet_by))` what you really need? Then you should consult the `facet_wrap()` and `vars()` documentation:

- https://ggplot2.tidyverse.org/reference/facet_wrap.html
- https://ggplot2.tidyverse.org/reference/vars.html
