### ISSUE TITLE
faux_cell dataset as parametrized function that generates data

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#154]
The size of `faux_cell` dataset is the same as of `chondro`:

```r
format(object.size(faux_cell), units = "MB")
#> [1] "2.1 Mb"

format(object.size(chondro), units = "MB")
#> [1] "2.1 Mb"
```

We can't load it as `data(faux_cell)`. And as `fauxCell` dataset is artificial, why don't we use it as a function, that generates data, e.g.: 

```r
faux_cell  <- hyperSpec::generate_faux_cell_data()
faux_cell  
```

**Comment by cbeleites** [comment]
Object size in memory is the same since it has the same dimensions as `chondro`.

It is already generated from function `.fauxCell()` via `delayedAssign()`, i.e. it is built (and starts to take memory) only when it is called for the fist time.

See https://github.com/cbeleites/hyperSpec/blob/develop/hyperSpec/R/fauxCell.R

**Comment by ximeg** [comment]
`fauxCell` returns a default dataset. We could make an addition function, e.g. `makeFauxCell` that accepts a set of arguments to parametrize the resulting dataset. If the arguments are not provided, then the resulting dataset is equal to the `fauxCell`.
