### ISSUE TITLE
What kind of object should flu[, "c", ] return?

### ISSUE THREAD

**Issue by bryanhanson** [cbeleites/hyperSpec#181]
As a irregular user of `hyperSpec` who is also editing vignettes with the eye of a new user, I'm going to have several questions about various functions.  My first one is in the title of this question.

What it currently returns doesn't make a lot of sense.  It seems to me that the either the return value should be changed, or if this operation is silly, it should be intercepted somehow and perhaps a warning issued.  Here's what it currently returns:

```
hyperSpec object
   6 spectra
   2 data columns
   0 data points / spectrum
wavelength: lambda/nm [numeric]
data:  (6 rows x 2 columns)
   1. c: c / (mg / l) [numeric] 0.05 0.10 ... 0.3 
   2. spc:  [matrix, array0]
```

It seems to have 6 empty spectra; I think `hyperSpec` objects must always have `x$spc` so maybe that's what's forcing the empty spectra.

**Comment by cbeleites** [comment]
The logic behind this is that `[...]` always returns a **hyperSpec** object, while `[[...]]` returns a data.frame or (matrix for the special case of `x[[]]`).

The behaviour for both is as similar as possible. 

So yes, since not giving `"spc"` in the columns to keep, the spectra matrix is emptied. This is by far not the only possibility to arrive at a hyperSpec object with empty spectra matrix (e.g. `flu[,,FALSE]`).

I cannot give an example right now where I use it, but do so very occasionally. `flu[,,FALSE]` is then typically the more convenient way for me to get empty spectra.

**Comment by bryanhanson** [comment]
Thanks.  Is there a case for warning the user in any of these possible cases that they have returned an object with empty spectra?

**Comment by ximeg** [comment]
I would prefer **not** to throw a warning. This is a logical behavior, and if this is done on purpose, the warnings would be annoying to deal with.

Most users would not use such syntax in their scripts (they'd be better served with `flu %>% select('c')`), and would most likely encounter such "strange" behavior during an interactive session, and would see the textual representation that says '0 data points / spectrum'.

**Comment by cbeleites** [comment]
@bryanhanson can we close this issue? If not, can you please put it on the agenda for tomorrow?
