### ISSUE TITLE
Why is the name of the wavelength label ".wavelength"?

### ISSUE THREAD

**Issue by bryanhanson** [cbeleites/hyperSpec#182]
This is a history question mainly.  Is there some reason it is not "wavelength"?

**Comment by cbeleites** [comment]
The original idea was to have the "visible" labels match the column names. 
The side thought was that it provides a slight informal guard against the possible conflict in case a user has an extra data column `$wavelength` (think fluorescence emission spectra, the user being somewhat lazy in using `$wavelength` rather than `$excitation_wavelength`).

See #90

**Comment by bryanhanson** [comment]
Thanks, looks like #90 covers the issues.
