### ISSUE TITLE
correct $spc column names for spc.*() functions

### ISSUE THREAD

**Issue by GregoryHuff** [cbeleites/hyperSpec#245]
I have been using spc.loess to smooth some spectra. I noticed that when I export them with write.table, the x-axis (which should be "wavelengths") is just the row number. I fixed this just by adding an extra line that probably shouldn't be necessary 
`colnames(x$spc) <- x@wavelength[]`

**Comment by cbeleites** [comment]
Thank you for bringing this to our attention. Indeed, we fixed a related bug only yesterday: https://github.com/cbeleites/hyperSpec/issues/237

@GegznaV would you have time to fix this like the other one?

@GregoryHuff are you aware of any other places where this happens? (This is really a bug only since we decided earlier this year that `colnames(spc)` should be "guaranteed").

And, since you seem to work with the colnames, have a look at https://github.com/cbeleites/hyperSpec/issues/232. We'll change the behaviour of `as.wide.df()` to allow easier interaction with models like `prcomp`.

**Comment by cbeleites** [comment]
@GregoryHuff we're in the middle of rather big transformations for **hyperSpec**, and right now IIRC the CRAN submission staff is in holidays. I therefore kindly ask you for some patience and to use your workaround possibly until we release **hyperSpec 1.0**.

**Comment by cbeleites** [comment]
TODO:

- [ ] fix `spc.loess()`, add unit test
- [ ] check & fix other `spc.*()` functions, add unit tests

**Comment by GegznaV** [comment]
@GregoryHuff could you provide a [reprex](https://reprex.tidyverse.org/) (minimal **repr**oducibe **ex**ample) that illustrates your issue?

**Comment by GegznaV** [comment]
Fixed in #247 

***

> check & fix other `spc.*()` functions, add unit tests (add lines above for functions that are done)

@cbeleites I'll open a new issue for this.

**Comment by GegznaV** [comment]
@GregoryHuff, I updated the instructions on how to install the development version of **hyperSpec** [here](https://cbeleites.github.io/hyperSpec/dev/). Can you confirm that your `spc.loess()` related issue is solved?
