### ISSUE TITLE
 there is no package called ‘rlang’

### ISSUE THREAD

**Issue by LDleo** [cbeleites/hyperSpec#76]
Dear all, the following message is showing up when loading hyperSpec.

Loading required package: hyperSpec
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘rlang’

**Comment by GegznaV** [comment]
Is `rlang` installed on your computer? Try to install or update it when thre are no other packages (especially `tidyverse` ones) loaded.

**Comment by cbeleites** [comment]
Hi LDLEo and thanks for using hyperSpec. 

`rlang` had an update to 0.2.1 yesterday. It can take a few days util the pre-compiled win and Mac binaries are available. 

- maybe the easiest way is to check again in a few days and update when the new binaries are available.
- to compile source packages you need tools that are not pre-installed on many machines.  
 Whether this is the issue with installing `rlang` from source or whether there are other difficulties I don't know - but that question is about [`rlang`](https://github.com/r-lib/rlang) rather than `hyperSpec`. It is a 3rd order dependency we get via `ggplot2`.  => I'll close this issue.  
BTW, there will be other changes upcoming with `ggplot2` in the near future, and in consequence, `hyperSpec` needs to have an update as well. That is submitted, but not yet on CRAN.

- for the future: in order to really check what is going on, we'd need the output of `sessionInfo ()`.

- > * removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rlang’ 
  This looks as if you're still using R 3.3. At some point you may need to consider updating (packages should state the R version they depend on, but changes are sometimes overlooked)
